# Generated by Django 2.2.7 on 2020-04-29 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(default=0)),
                ('hold_amount', models.IntegerField(default=0)),
                ('profit_amount', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('totla_loan_amount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pyments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pyment', models.IntegerField()),
                ('date', models.DateField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyments', to='API.Loan')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='API.Participants'),
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_hold_amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('reasoning', models.CharField(choices=[('capital increase', 'capital increase'), ('capital withdraw', 'capital withdraw'), ('throu loan', 'throu loan')], default='capital increase', max_length=120)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='API.Loan')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='API.Participants')),
            ],
        ),
    ]
