# Generated by Django 2.2.7 on 2020-04-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hold_amount',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hold_amount', to='API.Participants'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='API.Participants'),
        ),
    ]
