# Generated by Django 2.2.7 on 2020-05-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('reasoning', models.CharField(choices=[('capital increase', 'capital increase'), ('capital withdraw', 'capital withdraw'), ('loan pyment', 'loan pyment')], default='capital increase', max_length=120)),
                ('hold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashFlow', to='API.Hold')),
                ('pyment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashFlow', to='API.Pyments')),
            ],
        ),
    ]
