# Generated by Django 2.2.7 on 2020-04-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200420_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_hold_amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('reasoning', models.CharField(choices=[('capital increase', 'capital increase'), ('capital withdraw', 'capital withdraw'), ('throu loan', 'throu loan')], default='capital increase', max_length=120)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='API.Loan')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='API.Participants')),
            ],
        ),
        migrations.AlterField(
            model_name='pyments',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyments', to='API.Loan'),
        ),
        migrations.DeleteModel(
            name='Hold_amount',
        ),
    ]
