# Generated by Django 2.2.7 on 2020-05-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashFlow', to='API.Loan'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='reasoning',
            field=models.CharField(choices=[('capital increase', 'capital increase'), ('capital withdraw', 'capital withdraw'), ('loan pyment', 'loan pyment'), ('loan', 'loan')], max_length=120),
        ),
    ]
